# Generated by Django 2.2.24 on 2021-07-29 02:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0009_auto_20210504_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset', verbose_name='资产'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='comments',
            field=models.TextField(blank=True, default='n/a', null=True, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='risk_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='风险信息'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('info', 'info'), ('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], default='info', max_length=10, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='解决方案'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ack', 'Acknowledged'), ('mitigated', 'Mitigated'), ('confirmed', 'Confirmed'), ('patched', 'Patched'), ('closed', 'Closed'), ('false-positive', 'False-Positive'), ('undone', 'Undone'), ('duplicate', 'Duplicate')], default='new', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='title',
            field=models.CharField(default='title', max_length=256, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='type',
            field=models.CharField(max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='vuln_refs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Vuln参考'),
        ),
    ]
