# Generated by Django 2.2.24 on 2021-07-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20210402_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='categories',
            field=models.ManyToManyField(to='assets.AssetCategory', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='criticity',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.TextField(max_length=2048, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='value',
            field=models.TextField(max_length=2048, unique=True, verbose_name='值'),
        ),
    ]
