# Generated by Django 2.2.24 on 2021-11-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20210729_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='criticity',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='low', max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='exposure',
            field=models.CharField(choices=[('unknown', '未知'), ('external', '外部的'), ('internal', '内部的'), ('restricted', '受限制的')], default='unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('ip', 'ip地址'), ('ip-range', 'ip-范围(192.168.1.0-192.168.1.256)'), ('ip-subnet', 'ip-子网(192.168.1.0/24)'), ('fqdn', '全限定域名(fqdn)'), ('domain', '域名'), ('url', '网址'), ('keyword', '关键字'), ('person', '负责人(person)'), ('organisation', '组织(organisation)'), ('path', '路径(path)'), ('application', '应用(application)')], default='ip', max_length=15),
        ),
        migrations.AlterField(
            model_name='asset',
            name='value',
            field=models.TextField(max_length=2048, unique=True, verbose_name='资产值'),
        ),
        migrations.AlterField(
            model_name='assetgroup',
            name='criticity',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='None', max_length=10),
        ),
    ]
