# Generated by Django 2.2.24 on 2021-11-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20211125_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='value',
            field=models.TextField(max_length=2048, verbose_name='资产值'),
        ),
    ]
