# Generated by Django 2.2.24 on 2021-07-29 02:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='allowed_asset_types',
            field=models.TextField(null=True, verbose_name='允许的资产类型'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='engineinstance',
            name='api_url',
            field=models.CharField(max_length=256, verbose_name='API 地址'),
        ),
        migrations.AlterField(
            model_name='engineinstance',
            name='authentication_method',
            field=models.CharField(choices=[('None', 'None'), ('HTTPBasic', 'HTTPBasic'), ('APIKEY', 'APIKEY')], default='None', max_length=10, verbose_name='身份验证方法'),
        ),
        migrations.AlterField(
            model_name='engineinstance',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='engineinstance',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engines.Engine', verbose_name='引擎'),
        ),
        migrations.AlterField(
            model_name='engineinstance',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='enginepolicy',
            name='description',
            field=models.CharField(max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='enginepolicy',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engines.Engine', verbose_name='引擎'),
        ),
        migrations.AlterField(
            model_name='enginepolicy',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='./policies/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='enginepolicy',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='默认值'),
        ),
        migrations.AlterField(
            model_name='enginepolicy',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='enginepolicy',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='enginepolicy',
            name='scopes',
            field=models.ManyToManyField(to='engines.EnginePolicyScope', verbose_name='范围'),
        ),
    ]
