# Generated by Django 2.2.24 on 2021-11-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0002_auto_20210729_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineinstance',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='用户ID'),
        ),
    ]
